language: php
matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1
    fast_finish: true

env:
  global:
    TYPO3_PATH_WEB=`pwd`/.Build/Web
    typo3DatabaseName=lock
    typo3DatabaseHost=localhost
    typo3DatabaseUsername=root
    typo3DatabasePassword=''


services:
  - redis-server
  - mysql

before_install:
  - echo extension = redis.so >> $INI_FILE
  - echo extension = mysql.so >> $INI_FILE

install:
  - composer install
  - .Build/bin/phpunit