language: php
matrix:
    include:
        - php: 5.6
          env: DB=mysqli
        - php: 7.0
          env: DB=mysqli
        - php: 7.1
          env: DB=mysqli
    fast_finish: true

env:
  global:
    TYPO3_PATH_WEB=`pwd`/.Build/Web
    typo3DatabaseName=lock
    typo3DatabaseHost=localhost
    typo3DatabaseUsername=root
    typo3DatabasePassword=''
    typo3RedisHost=localhost
    typo3RedisDatabase=1


services:
  - redis-server
  - mysql

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - composer install
  - .Build/bin/phpunit